### ISSUE TITLE
引用的内容当中的有序序号换行问题

### ISSUE THREAD

**Issue by neoFelhz** [kokororin/typecho-plugin-Parsedown#3]
如果是在引用当中加上有序序号，效果就像这样：
![](https://img.imjad.cn/images/2016/10/06/01.png)
如果不是在引用当中加入有序序号，就不会两项之间空一行。

**Comment by neoFelhz** [comment]
准确点说凡是引用（qoute）的部分内，两段文字之间都会空一行出来。

**Comment by kokororin** [comment]
请确认下是不是主题的css问题。我这边测试是没问题的，如果我理解没错误的话
原文:

```
> 1. 测试测试测试测试测试测试测试测试测试测试测试11
> 2. 测试测试测试测试测试测试测试测试测试测试测试22
> 3. 测试测试测试测试测试测试测试测试测试测试测试33
```

转换后：

```

 <blockquote>
<ol>
<li>测试测试测试测试测试测试测试测试测试测试测试11</li>
<li>测试测试测试测试测试测试测试测试测试测试测试22</li>
<li>测试测试测试测试测试测试测试测试测试测试测试33</li>
</ol>
</blockquote>
```

如图：
![image](https://cloud.githubusercontent.com/assets/10093992/19152030/8e2f4e96-8c02-11e6-9b19-ea0c4b5ecde0.png)

**Comment by neoFelhz** [comment]
我看了一下，应该不是主题css的问题。
就是用了prasedown以后，不一定是有序序列，所有quote内的部分，两行之间都会空一行。

**Comment by kokororin** [comment]
希望能给出你的markdown原文，同时也请复制下解析后的html代码

**Comment by neoFelhz** [comment]
https://neofelhz.labodev.xyz/index.php/archives/29/
我专门开了一篇文章测试了一下。

这是我用的代码：

![](https://img.imjad.cn/images/2016/10/07/Screenshot_20161007-175046.png)

**Comment by neoFelhz** [comment]
在显示时，应用内的列表的两段之间的空行有两个空格。
在未启用插件时两段之间是没有空段落的。

**Comment by kokororin** [comment]
图挂了……

**Comment by kokororin** [comment]
目测差不多是这样，我测试一下

```
> 这是没有序列的，  
> 可以看的出来两段之间没有空行。  
> 这三段开头都有引用符。

---

> 如果分段的时候，  
> 只有第一段有引用符，  
> 那么就像这样。

---

> *   如果把bullet list加进来，
> *   就像这样。
> *   这三段只有第一段有引用符。

---

> *   如果把bullet list加进来，
> *   就像这样。
> *   这三段每一段都有引用符。

---

> 1.  如果把有序序列加进来，
> 2.  就像这样。
> 3.  这三段只有第一段都有引用符。

---

> 1.  如果把有序序列加进来，
> 2.  就像这样。
> 3.  这三段每一段都有引用符。
```

> 这是没有序列的，  
> 可以看的出来两段之间没有空行。  
> 这三段开头都有引用符。

---

> 如果分段的时候，  
> 只有第一段有引用符，  
> 那么就像这样。

---

> -   如果把bullet list加进来，
> -   就像这样。
> -   这三段只有第一段有引用符。

---

> -   如果把bullet list加进来，
> -   就像这样。
> -   这三段每一段都有引用符。

---

> 1.  如果把有序序列加进来，
> 2.  就像这样。
> 3.  这三段只有第一段都有引用符。

---

> 1.  如果把有序序列加进来，
> 2.  就像这样。
> 3.  这三段每一段都有引用符。

**Comment by kokororin** [comment]
表示真的和css有关，
例如下一段文本

```
> *   如果把bullet list加进来，
> *   就像这样。
> *   这三段只有第一段有引用符。
```

Typecho自带的转换库将转换为

```
<blockquote>
  <ul>
    <li>
      <p>如果把bullet list加进来，</p>
    </li>
    <li>
      <p>就像这样。</p>
    </li>
    <li>
      <p>这三段只有第一段有引用符。</p>
    </li>
  </ul>
</blockquote>
```

而Parsedown将转换为

```
<blockquote>
  <ul>
    <li>如果把bullet list加进来，</li>
    <li>就像这样。</li>
    <li>这三段每一段都有引用符。</li>
  </ul>
</blockquote>
```

可以看出区别
Typecho自带的会把<li>标签内再包裹一层<p>

**Comment by neoFelhz** [comment]
我回头再看看css吧。
