### ISSUE TITLE
能否把目前这个Parserdown.php换成最新版？

### ISSUE THREAD

**Issue by medmin** [kokororin/typecho-plugin-Parsedown#8]
谢谢

我意思 是，我可以自己来替换吗？谢谢

**Comment by kokororin** [comment]
自己替换就行了

**Comment by medmin** [comment]
请教一下，这个库比typecho自带的好在哪里呢？谢谢

**Comment by kokororin** [comment]
原版为了适配SF，做了很多改动，不符合markdown规范，如果没有体验到差别的话，用原版问题也不大。
比如
```
* A
* B
```
会解析成
```
<li><p>A</p></li>
<li><p>B</p></li>
```
这里的p标签是没有必要的，有可能会造成主题格式错乱

**Comment by medmin** [comment]
目前确实尚未体会到差别。。。。

感谢解答！

**Comment by medmin** [comment]
已经用了，感觉很好，非常靠谱，确实比原声的md解析库还用，解析出来的格式好看多了。

**Comment by medmin** [comment]
感谢
